// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ad a discount code', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ad a discount code', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(1299, 741)
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6) > .MuiListItemText-root")).click()
    await driver.executeScript("window.scrollTo(0,15)")
    await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(2) > .RuiSidebar-listItemNested-84 > .MuiListItemText-root")).click()
    await driver.executeScript("window.scrollTo(0,424)")
    await driver.findElement(By.css(".btn-default")).click()
    {
      const element = await driver.findElement(By.css(".btn-default"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("k9ytfFYKZmYQFrqhu")).click()
    await driver.findElement(By.id("k9ytfFYKZmYQFrqhu")).sendKeys("usama")
    await driver.findElement(By.id("WydkWQMe2h8tDy4c2")).sendKeys("12")
    await driver.findElement(By.id("b2DGexkoLXMq7e78y")).click()
    await driver.findElement(By.id("b2DGexkoLXMq7e78y")).sendKeys("12")
    await driver.findElement(By.id("8gu2vFKbXb2SMiB8r")).sendKeys("24")
    {
      const element = await driver.findElement(By.id("kTCtyueoThqWyki7w"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("kTCtyueoThqWyki7w"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("kTCtyueoThqWyki7w"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("kTCtyueoThqWyki7w")).click()
    await driver.findElement(By.css(".pull-right > .btn:nth-child(2)")).click()
    await driver.executeScript("window.scrollTo(0,621)")
  })
})
