// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('add shipping', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('add shipping', async function() {
    await driver.get("http://localhost:3000/operator/shipping")
    await driver.manage().window().setRect(1299, 741)
    await driver.findElement(By.css(".css-19bqh2r")).click()
    {
      const element = await driver.findElement(By.id("react-select-2-option-0"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("react-select-2-option-0"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("react-select-2-option-0"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("react-select-2-option-0")).click()
    {
      const element = await driver.findElement(By.id("cost_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("cost_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("cost_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("cost_ShippingMethodForm1")).click()
    await driver.findElement(By.id("cost_ShippingMethodForm1")).sendKeys("50")
    await driver.findElement(By.id("cost_ShippingMethodForm1")).sendKeys("50")
    await driver.findElement(By.id("cost_ShippingMethodForm1")).sendKeys("50")
    {
      const element = await driver.findElement(By.css(".Field__StyledField-qlv3w9-0:nth-child(5) > .TextInput__InputWrapper-sc-9jjo1u-0"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".Field__StyledField-qlv3w9-0:nth-child(5) > .TextInput__InputWrapper-sc-9jjo1u-0"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".Field__StyledField-qlv3w9-0:nth-child(5) > .TextInput__InputWrapper-sc-9jjo1u-0"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".Field__StyledField-qlv3w9-0:nth-child(5) > .TextInput__InputWrapper-sc-9jjo1u-0")).click()
    {
      const element = await driver.findElement(By.id("handling_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("handling_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("handling_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".Field__StyledField-qlv3w9-0:nth-child(5) > .TextInput__InputWrapper-sc-9jjo1u-0")).click()
    {
      const element = await driver.findElement(By.id("handling_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("handling_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("handling_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("handling_ShippingMethodForm1")).click()
    await driver.findElement(By.id("handling_ShippingMethodForm1")).sendKeys("5.5")
    await driver.findElement(By.id("handling_ShippingMethodForm1")).sendKeys("5.5")
    await driver.findElement(By.id("handling_ShippingMethodForm1")).sendKeys("5.5")
    {
      const element = await driver.findElement(By.id("rate_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("rate_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("rate_ShippingMethodForm1"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("rate_ShippingMethodForm1")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-contained > .MuiButton-label"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("rate_ShippingMethodForm1")).sendKeys("500")
    await driver.findElement(By.id("rate_ShippingMethodForm1")).sendKeys("500")
    await driver.findElement(By.id("rate_ShippingMethodForm1")).sendKeys("500")
    {
      const element = await driver.findElement(By.css(".MuiButton-contained > .MuiButton-label"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiButton-contained > .MuiButton-label"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiButton-contained > .MuiButton-label"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.css(".MuiButton-contained > .MuiButton-label")).click()
  })
})
