// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('change cuurency', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('change cuurency', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(1299, 741)
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6) > .MuiListItemText-root")).click()
    await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(7) .MuiListItemText-root > span")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".css-1gtu0rj-indicatorContainer > .css-tj5bde-Svg")).click()
    await driver.findElement(By.id("react-select-3-option-4")).click()
  })
})
