// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('shopping', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('shopping', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(1299, 741)
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6)")).click()
    await driver.findElement(By.id("dSyCiaJDpavaqau2f")).click()
    await driver.findElement(By.id("dSyCiaJDpavaqau2f")).sendKeys("shoes")
    await driver.findElement(By.id("guGgfZL3ga5kkGGX8")).click()
    await driver.findElement(By.id("guGgfZL3ga5kkGGX8")).sendKeys("sweade")
    await driver.findElement(By.id("uaPotbaguokfKtEQG")).click()
    await driver.findElement(By.id("uaPotbaguokfKtEQG")).sendKeys("1255")
    await driver.findElement(By.css(".clearfix:nth-child(6) > .btn")).click()
  })
})
