// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('tax rate', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('tax rate', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(1299, 741)
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6)")).click()
    await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(3) > .RuiSidebar-listItemNested-84 > .MuiListItemText-root")).click()
    await driver.findElement(By.id("defaultTaxCode_GeneralTaxSettings1")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-label"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.id("defaultTaxCode_GeneralTaxSettings1")).sendKeys("540")
    await driver.findElement(By.css(".MuiButton-label")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
